### ISSUE TITLE
test-e2e should be idempotent

### ISSUE THREAD

**Issue by djzager** [konveyor/tackle2-addon-windup#64]
It would be helpful, in the long run, if the `hack/test-e2e.sh` were idempotent. This would allow a developer to test their changes locally by iterating on the addon and running the e2e test. Additionally, it would allow for integration testing where multiple addons would be tested in the same cluster using a single instance of the hub.

**Comment by mundra-ankur** [comment]
I believe this issue is taken care of as part of [test-e2e as GitHub Action](https://github.com/konveyor/tackle2-addon-windup/issues/63 )
- Developers can clone this repo and if the tackle environment is ready they can run this [script](https://github.com/konveyor/tackle2-addon-windup/blob/main/hack/test-e2e.sh) and test their addon
- Also, integration testing is proved as part of [Test windup addon](https://github.com/konveyor/tackle2-hub/issues/170)

**Comment by jortel** [comment]
Only the application is needed to test the windup addon.  If that helps ...
